channels:
- pytorch
- plotly
- nvidia
- conda-forge
- defaults
dependencies:
- black=23.7.0
- fastparquet=2023.8.0
- isort=5.12.0
- jupyterlab=4.0.5
- mamba=1.4.9
- matplotlib=3.7.2
- numpy=1.24.3
- pandas=2.0.3
- pyarrow=11.0.0
- pytorch=2.0.1
- pytorch-lightning=2.0.9
- rich=13.5.3
- scanpy=1.9.3
- scikit-misc=0.1.4
- pip:
  - ipywidgets
  - gseapy
  - ipympl
